citesc CSV-urile originale

In [6]:
import pandas as pd

fake = pd.read_csv("../data/Fake.csv")
true = pd.read_csv("../data/True.csv")

print("Fake: ", fake.shape)
print("True: ", true.shape)

fake.head()

Fake:  (23481, 4)
True:  (21417, 4)

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

pun label-uri 
fake -> 0
true -> 1

In [7]:
fake["label"] = 0
true["label"] = 1 

df = pd.concat([fake, true], ignore_index=True)

print(df.shape)
print(df["label"].value_counts())
df.head()

(44898, 5)
label
0    23481
1    21417
Name: count, dtype: int64

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

creez coloana content

In [8]:
df["title"] = df["title"].fillna("")
df["text"] = df["text"].fillna("")

df["content"] = df["title"] + " " + df["text"]

df[["content", "label"]].head()

                                             content  label
0   Donald Trump Sends Out Embarrassing New Year’...      0
1   Drunk Bragging Trump Staffer Started Russian ...      0
2   Sheriff David Clarke Becomes An Internet Joke...      0
3   Trump Is So Obsessed He Even Has Obama’s Name...      0
4   Pope Francis Just Called Out Donald Trump Dur...      0

curat textul

In [9]:
import re

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+|www\S+", "", text)
    text = re.sub(r"[^a-zA-Z\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df["clean_content"] = df["content"].apply(clean_text)

df[["content", "clean_content", "label"]].head()

,content,clean_content,label
0,Donald Trump Sends Out Embarrassing New Year’...,donald trump sends out embarrassing new year s...,0
1,Drunk Bragging Trump Staffer Started Russian ...,drunk bragging trump staffer started russian c...,0
2,Sheriff David Clarke Becomes An Internet Joke...,sheriff david clarke becomes an internet joke ...,0
3,Trump Is So Obsessed He Even Has Obama’s Name...,trump is so obsessed he even has obama s name ...,0
4,Pope Francis Just Called Out Donald Trump Dur...,pope francis just called out donald trump duri...,0

fac subset mai mic -> ca sa nu imi ia atata de mult

In [10]:
fake_sample = df[df["label"] == 0].sample(3000, random_state=42)
true_sample = df[df["label"] == 1].sample(3000, random_state=42)

df_small = pd.concat([fake_sample, true_sample], ignore_index=True)
df_small = df_small.sample(frac=1, random_state=42).reset_index(drop=True)

print(df_small.shape)
print(df_small["label"].value_counts())

(6000, 7)
label
0    3000
1    3000
Name: count, dtype: int64

salvez csv termporar (ca sa pot lucra eu pe partea mea pana face persoana 1)

In [11]:
df_small[["content", "clean_content", "label"]].to_csv(
    "../data/processed_news.csv",
    index=False
)

print("Temporary processed_news.csv created.")

Temporary processed_news.csv created.

verific daca e ok

In [ ]:
# test_df = pd.read_csv("../data/processed_news.csv")

print(test_df.shape)
print(test_df.head())

TASK 1: citesc processed_news.csv

In [13]:
import pandas as pd

df = pd.read_csv("../data/processed_news.csv")

df.head()

,content,clean_content,label
0,WATCH: Trump Just Told All The Anti-Gay Bigot...,watch trump just told all the anti gay bigots ...,0
1,"China backs U.N. call for justice in Yemen, U....",china backs u n call for justice in yemen u s ...,1
2,THE PEOPLE’S PRESIDENT: Trump Meets With Coal ...,the people s president trump meets with coal w...,0
3,WSJ REPORTER RIPS INTO DEM CANDIDATES For Thei...,wsj reporter rips into dem candidates for thei...,0
4,Lawmakers aim to delay U.S. ceding control of ...,lawmakers aim to delay u s ceding control of i...,1

TASK 2: verific coloanele